<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-DM7HA6N" failures="1" tests="1" name="day3Jul23.SoftAssertionDemo" time="0.019" errors="0" timestamp="2023-07-03T13:28:43 IST" skipped="0">
  <testcase classname="day3Jul23.SoftAssertionDemo" name="verifySoftAssertion1" time="0.019">
    <failure message="Few SOFT Assertions are failed
	a != b expected [15] but found [13],
	f1!=f2 expected [12.35] but found [12.3589],
	s is not null expected [null] but found [Cyber],
	c is equal to d did not expect [3] but found [3],
	Stud1 != Stud2 expected [Student [id=1, name=Siddesh1]] but found [Student [id=1, name=Siddesh]]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Few SOFT Assertions are failed
a != b expected [15] but found [13],
f1!=f2 expected [12.35] but found [12.3589],
s is not null expected [null] but found [Cyber],
c is equal to d did not expect [3] but found [3],
Stud1 != Stud2 expected [Student [id=1, name=Siddesh1]] but found [Student [id=1, name=Siddesh]]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at day3Jul23.SoftAssertionDemo.verifySoftAssertion1(SoftAssertionDemo.java:75)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifySoftAssertion1 -->
  <system-out/>
</testsuite> <!-- day3Jul23.SoftAssertionDemo -->
